server:
  port: 9011
spring:
  application:
    name: register          #name必须一样，不然高可用会导致unavailable-replicas
eureka:
  instance:
    hostname: register2
  client:
    register-with-eureka: true #这里要覆盖application的设置，不然会读取application文件导致unavailable-replicas
    fetch-registry: true  #这里要覆盖application的设置，不然会读取application文件导致unavailable-replicas
    service-url:
      defaultZone: http://register1:9010/eureka/
debug: true